<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <title>HWACKER Workflow</title>
  <style>
    body {
      <meta charset="UTF-8">
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy static site to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./  # change if your site is in a subfolder like /dist or /docs

      background-color: #f5f5f5;
      padding: 40px;
    }

    .workflow {
      display: flex;
      flex-wrap: wrap;
      justify-content: center;
      gap: 30px;
    }

    .step {
      background-color: #ffffff;
      border: 2px solid #005599;
      border-radius: 8px;
      padding: 20px;
      width: 200px;
      text-align: center;
      position: relative;
    }

    .step h3 {
      margin: 10px 0;
      color: #003366;
    }

    .arrow::after {
      content: "➡";
      position: absolute;
      right: -30px;
      top: 35%;
      font-size: 24px;
      color: #005599;
    }

    .workflow .step:last-child .arrow::after {
      content: "";
    }

    @media (max-width: 768px) {
      .workflow {
        flex-direction: column;
        align-items: center;
      }

      .arrow::after {
        content: "⬇";
        position: absolute;
        left: 50%;
        top: 100%;
        transform: translateX(-50%);
      }

      .workflow .step:last-child .arrow::after {
        content: "";
      }
    }
  </style>
</head>
<body>

  <h1 style="text-align: center; color: #003366;">HWACKER Website Workflow</h1>

  <div class="workflow">
    <div class="step arrow">
      <h3>Home</h3>
      <p>Welcome message, vision & tagline</p>
    </div>
    <div class="step arrow">
      <h3>About</h3>
      <p>Who we are and what we do</p>
    </div>
    <div class="step arrow">
      <h3>Services</h3>
      <p>Cybersecurity & Cyber Law offerings</p>
    </div>
    <div class="step arrow">
      <h3>Resources</h3>
      <p>Insights, updates & legal guides</p>
    </div>
    <div class="step arrow">
      <h3>Support Staff</h3>
      <p>Meet the team behind the mission</p>
    </div>
    <div class="step">
      <h3>Contact</h3>
      <p>Email, phone, or connect with us</p>
    </div>
  </div>

</body>
</html>
